spring.application.name=Oauth2

server.port = 8000

spring.security.oauth2.client.registration.google.client-id= 780011879868-ul6pu15r6oicgi38rccn28td9np8774k.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret= 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

spring.security.oauth2.client.registration.github.client-id= Ov23liIsUKYWa1xI0Bza
spring.security.oauth2.client.registration.github.client-secret= 466c841316457b8d8340f898f207ae10461b1eb3
